### PR TITLE
Feature/delete

### PR DESCRIPTION
**Pull request by Feudalman**
## Description

1. User can delete project with the delete button on SwanLab dashboard, and also the experiments.
2. Error page for common errors.
3. Placeholder while no experiments.

Closes: #128

### CODE REVIEW

**Comment by xiaolin199912** [comment]
语言修改：
image

标题改为"Delete this project"
描述文本改为"Once you delete a repository, there is no going back. Please be certain."

**Comment by xiaolin199912** [comment]
v0.1.2beta3改进：
1. 统一「修改」与「删除」组件UI

**Comment by Feudalman** [comment]
> 语言修改： image
> 
> 标题改为"Delete this project" 描述文本改为"Once you delete a repository, there is no going back. Please be certain."

已修改

**Comment by Feudalman** [comment]
> v0.1.2beta3改进：
> 
> 1. 增加删除成功的气泡弹窗
> 2. 统一「修改」与「删除」组件UI
> 3. Hover图表时，本来是保留6位小数，这版本好像没了
> 4. 停止实验时，本来状态是Crashed，这版本变成Finish了
> 5. 实验列表也需要个占位（下图发生在删除所有实验，但未实验项目时）：
> 
> image

1,2,5 已解决，3，4 计划在另外分支处理

**Review by SAKURA-CAT — APPROVED** [review]

**Pull request merged**
